import { AbortSignal } from '@dynatrace-sdk/http-client';
import { GetHostsWithSpecificAgentsQueryAgentVersionIs } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryAutoInjection } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryAutoUpdateSetting } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryAvailabilityState } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryCloudType } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryDetailedAvailabilityState } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryMonitoringType } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryOsType } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryPluginState } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryPluginVersionIs } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryRelativeTime } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryTechnologyModuleType } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryTechnologyModuleVersionIs } from "@dynatrace-sdk/client-classic-environment-v1"; 
import { GetHostsWithSpecificAgentsQueryUpdateStatus } from "@dynatrace-sdk/client-classic-environment-v1"; 

export type OneAgentOnAHostConfig = {
    includeDetails?: boolean;
    startTimestamp?: number;
    endTimestamp?: number;
    relativeTime?: GetHostsWithSpecificAgentsQueryRelativeTime;
    tag?: string[];
    entity?: string[];
    managementZoneId?: number;
    managementZone?: string;
    networkZoneId?: string;
    hostGroupId?: string;
    hostGroupName?: string;
    osType?: GetHostsWithSpecificAgentsQueryOsType;
    cloudType?: GetHostsWithSpecificAgentsQueryCloudType;
    autoInjection?: GetHostsWithSpecificAgentsQueryAutoInjection;
    availabilityState?: GetHostsWithSpecificAgentsQueryAvailabilityState;
    detailedAvailabilityState?: GetHostsWithSpecificAgentsQueryDetailedAvailabilityState;
    monitoringType?: GetHostsWithSpecificAgentsQueryMonitoringType;
    agentVersionIs?: GetHostsWithSpecificAgentsQueryAgentVersionIs;
    agentVersionNumber?: string;
    autoUpdateSetting?: GetHostsWithSpecificAgentsQueryAutoUpdateSetting;
    updateStatus?: GetHostsWithSpecificAgentsQueryUpdateStatus;
    faultyVersion?: boolean;
    activeGateId?: string;
    technologyModuleType?: GetHostsWithSpecificAgentsQueryTechnologyModuleType;
    technologyModuleVersionIs?: GetHostsWithSpecificAgentsQueryTechnologyModuleVersionIs;
    technologyModuleVersionNumber?: string;
    technologyModuleFaultyVersion?: boolean;
    pluginName?: string;
    pluginVersionIs?: GetHostsWithSpecificAgentsQueryPluginVersionIs;
    pluginVersionNumber?: string;
    pluginState?: GetHostsWithSpecificAgentsQueryPluginState;
    nextPageKey?: string;
    abortSignal?: AbortSignal;
}